apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: web-app
type: Opaque
data:
  # Base64 encoded values
  # username: admin (encoded)
  username: YWRtaW4=
  # password: secretpassword (encoded)
  password: c2VjcmV0cGFzc3dvcmQ=
  # database-url: postgresql://user:pass@host:5432/db (encoded)
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bob3N0OjU0MzIvZGI=
  # api-key: your-secret-api-key (encoded)
  api-key: eW91ci1zZWNyZXQtYXBpLWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    app: web-app
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==
