apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: config-demo
type: Opaque
data:
  # Los valores están codificados en base64
  # Para generar: echo -n "valor" | base64
  api_key: bWktYXBpLWtleS1zZWNyZXRv          # mi-api-key-secreto
  database_password: bXlwYXNzd29yZA==        # mypassword
  jwt_secret: c3VwZXItc2VjcmV0LWp3dC1rZXk=    # super-secret-jwt-key
  
stringData:
  # Alternativamente, puedes usar stringData para valores en texto plano
  # Kubernetes los codificará automáticamente
  admin_email: "admin@example.com"
  smtp_password: "smtp-password-123"
