# Kubespray Inventory - Alta Disponibilidad
# Configuración para cluster de producción con 3 masters y 5 workers

all:
  hosts:
    # Control Plane Nodes (Masters)
    master1:
      ansible_host: 10.0.1.10
      ip: 10.0.1.10
      access_ip: 10.0.1.10
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    master2:
      ansible_host: 10.0.1.11
      ip: 10.0.1.11
      access_ip: 10.0.1.11
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    master3:
      ansible_host: 10.0.1.12
      ip: 10.0.1.12
      access_ip: 10.0.1.12
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    # Worker Nodes
    worker1:
      ansible_host: 10.0.1.20
      ip: 10.0.1.20
      access_ip: 10.0.1.20
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    worker2:
      ansible_host: 10.0.1.21
      ip: 10.0.1.21
      access_ip: 10.0.1.21
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    worker3:
      ansible_host: 10.0.1.22
      ip: 10.0.1.22
      access_ip: 10.0.1.22
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    worker4:
      ansible_host: 10.0.1.23
      ip: 10.0.1.23
      access_ip: 10.0.1.23
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    worker5:
      ansible_host: 10.0.1.24
      ip: 10.0.1.24
      access_ip: 10.0.1.24
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

    # External Load Balancer (opcional)
    # Descomenta si usas un LB externo para el API server
    # lb1:
    #   ansible_host: 10.0.1.5
    #   ip: 10.0.1.5
    #   access_ip: 10.0.1.5
    #   ansible_user: ubuntu

  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    
    kube_node:
      hosts:
        worker1:
        worker2:
        worker3:
        worker4:
        worker5:
    
    etcd:
      hosts:
        master1:
        master2:
        master3:
    
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    
    # Para clusters grandes con Calico
    calico_rr:
      hosts: {}
    
    # Uncomment if using external load balancer
    # kube_control_plane_lb:
    #   hosts:
    #     lb1:

  vars:
    # Variables globales para todos los hosts
    ansible_python_interpreter: /usr/bin/python3
    
    # Configuración de red
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    
    # Configuración de contenedores
    container_manager: containerd
    
    # Configuración de red del cluster
    kube_network_plugin: calico
    kube_service_addresses: 10.233.0.0/18
    kube_pods_subnet: 10.233.64.0/18
    
    # Configuración de API server
    # Si usas un load balancer externo, descomenta y configura:
    # kube_apiserver_ip: 10.0.1.5
    # kube_apiserver_port: 6443
    # kube_apiserver_access_addresses:
    #   - 10.0.1.5
    
    # Configuración de alta disponibilidad
    kube_control_plane_lb: true
    
    # Configuración de storage
    kube_controller_manager_bind_address: 0.0.0.0
    kube_scheduler_bind_address: 0.0.0.0
    
    # Configuración de logs y métricas
    kubelet_deployment_type: host
    docker_daemon_graph: "/var/lib/docker"
    
    # Timeouts y limits
    kube_apiserver_request_timeout: "300s"
    etcd_snapshot_count: 10000
