apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
# Opcional: LoadBalancer para acceso externo
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-external
#   namespace: monitoring
#   labels:
#     app: prometheus
# spec:
#   selector:
#     app: prometheus
#   ports:
#   - name: web
#     port: 9090
#     targetPort: 9090
#     protocol: TCP
#   type: LoadBalancer
