apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app: local-path-provisioner
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false

---
# StorageClass alternativa con retención de datos
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-retain
  labels:
    app: local-path-provisioner
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain  # Los datos no se eliminan al borrar PVC
allowVolumeExpansion: false

---
# StorageClass para bases de datos (binding inmediato)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-database
  labels:
    app: local-path-provisioner
    usage: database
provisioner: rancher.io/local-path
volumeBindingMode: Immediate  # Binding inmediato para DBs
reclaimPolicy: Retain
allowVolumeExpansion: false
