apiVersion: v1
kind: Pod
metadata:
  name: test-local-storage
  labels:
    app: test-storage
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    volumeMounts:
    - name: web-data
      mountPath: /usr/share/nginx/html
    - name: logs
      mountPath: /var/log/nginx
    # Inicializar con contenido
    command: ["/bin/sh"]
    args:
      - -c
      - |
        echo "<h1>Test Local Storage</h1>" > /usr/share/nginx/html/index.html
        echo "<p>Fecha: $(date)</p>" >> /usr/share/nginx/html/index.html
        echo "<p>Pod: $HOSTNAME</p>" >> /usr/share/nginx/html/index.html
        nginx -g 'daemon off;'
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  volumes:
  - name: web-data
    persistentVolumeClaim:
      claimName: test-pvc-basic
  - name: logs
    emptyDir: {}
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: test-storage-service
  labels:
    app: test-storage
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: test-storage
