apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-basic
  labels:
    app: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  labels:
    app: mysql
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-database
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  labels:
    app: backup
    retention: permanent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 5Gi
