apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: web-app
data:
  # Configuración de la aplicación
  app.properties: |
    app.name=MyWebApp
    app.version=1.0.0
    app.environment=production
    app.debug=false
    
    # Database configuration
    db.host=database-service
    db.port=5432
    db.name=myapp
    
    # Cache configuration
    cache.enabled=true
    cache.ttl=3600
    
  # Configuración de logging
  log4j.properties: |
    log4j.rootLogger=INFO, stdout, file
    
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    
    log4j.appender.file=org.apache.log4j.FileAppender
    log4j.appender.file.File=/var/log/app.log
    log4j.appender.file.layout=org.apache.log4j.PatternLayout
    log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    
  # Variables individuales
  APP_NAME: "MyWebApp"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  MAX_CONNECTIONS: "100"
