apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: config-demo
data:
  # Configuración de la aplicación
  database_url: "mysql://mysql-service:3306/myapp"
  log_level: "info"
  max_connections: "100"
  timeout: "30"
  
  # Archivo de configuración completo
  app.properties: |
    # Configuración de la aplicación
    database.url=mysql://mysql-service:3306/myapp
    database.pool.size=10
    database.timeout=30
    
    # Configuración de logging
    log.level=info
    log.format=json
    
    # Configuración de la API
    api.version=v1
    api.rate_limit=1000
    
    # Configuración de cache
    cache.enabled=true
    cache.ttl=3600
  
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            proxy_pass http://backend-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /health {
            access_log off;
            return 200 "OK\n";
            add_header Content-Type text/plain;
        }
    }
