apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: web-app
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: content-generator
    image: busybox:1.35
    command: ["/bin/sh"]
    args:
      - -c
      - |
        while true; do
          echo "<h1>Hello from multi-container pod!</h1>" > /shared/index.html
          echo "<p>Generated at $(date)</p>" >> /shared/index.html
          sleep 30
        done
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  volumes:
  - name: shared-data
    emptyDir: {}
